//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolnica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_karta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Med_karta()
        {
            this.Zapis = new HashSet<Zapi>();
            this.Spisok_lekarstv = new HashSet<Spisok_lekarstv>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Vrach { get; set; }
        public string Jalobi { get; set; }
        public Nullable<int> ID_Diagnoza { get; set; }
        public Nullable<System.DateTime> Date_posehenia { get; set; }
        public string Naznachenie { get; set; }
    
        public virtual Spisok_diagnozov Spisok_diagnozov { get; set; }
        public virtual Vrachi Vrachi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapi> Zapis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spisok_lekarstv> Spisok_lekarstv { get; set; }
    }
}
