//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolnica.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoolEntities : DbContext
    {
        public BoolEntities()
            : base("name=BoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Med_karta> Med_karta { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Spisok_diagnozov> Spisok_diagnozov { get; set; }
        public virtual DbSet<Spisok_lekarstv> Spisok_lekarstv { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vrachi> Vrachis { get; set; }
        public virtual DbSet<Zapi> Zapis { get; set; }
    }
}
